pub enum Header {
    TrainFrom,
    TrainTo,
    TrainDate,
    CustomerReference,
    TfgReference,
    CustomerName,
    TruckerCode,
    TransportInstructions,
    DepotReference,
    ContainerPrefix,
    ContainerNumber,
    ContainerType,
    ContainerHeight,
    ContainerLength,
    ContainerWeight,
    ContainerContentWeight,
    Customs,
    Shipper,
    Content,
    AddressOneName,
    AddressOneStreet,
    AddressOneTown,
    AddressOneZipcode,
    AddressOneCountry,
    AddressOneDate,
    AddressOneTime,
    AddressTwoName,
    AddressTwoStreet,
    AddressTwoTown,
    AddressTwoZipcode,
    AddressTwoCountry,
    AddressTwoDate,
    AddressTwoTime,
    AddressThreeName,
    AddressThreeStreet,
    AddressThreeTown,
    AddressThreeZipcode,
    AddressThreeCountry,
    AddressThreeDate,
    AddressThreeTime,
}

impl Header {
    const fn as_str(self) -> &'static str {
        match self {
            Self::TrainFrom => "Abgangsbhf-Nr.",
            Self::TrainTo => "Zielbhf.-Nr.",
            Self::TrainDate => "Versandtag",
            Self::CustomerReference => "KundenRef.",
            Self::TfgReference => "TFG Ref.",
            Self::CustomerName => "Kundenname",
            Self::TruckerCode => "VU Code",
            Self::TransportInstructions => "Frachtbrieferklärung",
            Self::DepotReference => "DepotRef",
            Self::ContainerPrefix => "Ctr.Präfix",
            Self::ContainerNumber => "Ctr.nr",
            Self::ContainerType => "Ct. Typ",
            Self::ContainerHeight => "Ct. Höhe",
            Self::ContainerLength => "Ct. Länge",
            Self::ContainerWeight => "Ct. Tara",
            Self::ContainerContentWeight => "Ct. Inhalt Gew",
            Self::Customs => "Zollverfahren",
            Self::Shipper => "Reeder",
            Self::Content => "Warenbeschreibung",
            Self::AddressOneName => "AdressName_1",
            Self::AddressOneStreet => "Strasse_1",
            Self::AddressOneTown => "Ort_1",
            Self::AddressOneZipcode => "PLZ_1",
            Self::AddressOneCountry => "Land_1",
            Self::AddressOneDate => "Termin_1",
            Self::AddressOneTime => "Uhrzeit_1",
            Self::AddressTwoName => "AdressName_2",
            Self::AddressTwoStreet => "Strasse_2",
            Self::AddressTwoTown => "Ort_2",
            Self::AddressTwoZipcode => "PLZ_2",
            Self::AddressTwoCountry => "Land_2",
            Self::AddressTwoDate => "Termin_2",
            Self::AddressTwoTime => "Uhrzeit_2",
            Self::AddressThreeName => "AdressName_3",
            Self::AddressThreeStreet => "Strasse_3",
            Self::AddressThreeTown => "Ort_3",
            Self::AddressThreeZipcode => "PLZ_3",
            Self::AddressThreeCountry => "Land_3",
            Self::AddressThreeDate => "Termin_3",
            Self::AddressThreeTime => "Uhrzeit_3",
        }
    }
}

pub struct Item {
    train_from: String,
    train_to: String,
    train_date: String,
    customer_reference: String,
    tfg_reference: String,
    customer_name: String,
    trucker_code: String,
    transport_instructions: String,
    depot_reference: String,
    container_prefix: String,
    container_number: String,
    container_type: String,
    container_height: String,
    container_length: String,
    container_weight: String,
    container_content_weight: String,
    customs: String,
    shipper: String,
    content: String,
    address_one_name: String,
    address_one_street: String,
    address_one_town: String,
    address_one_zipcode: String,
    address_one_country: String,
    address_one_date: String,
    address_one_time: String,
    address_two_name: String,
    address_two_street: String,
    address_two_town: String,
    address_two_zipcode: String,
    address_two_country: String,
    address_two_date: String,
    address_two_time: String,
    address_three_name: String,
    address_three_street: String,
    address_three_town: String,
    address_three_zipcode: String,
    address_three_country: String,
    address_three_date: String,
    address_three_time: String,
}

impl Item {
    pub fn new(train_from: String) -> Item {
        Item {
            train_from: train_from,
            ..
        }
    }
}
